/** Ordre parents → enfants (doit matcher le backend SYNC_ENTITY_DEFS). */
export const ENTITY_ORDER = [
  'SchoolProfile',
  'User',
  'AcademicYear',
  'Period',
  'Room',
  'Subject',
  'Class',
  'ClassSubject',
  'Student',
  'FeeService',
  'ClassFee',
  'ClassSubjectCoefficient',
  'ExamSchedule',
  'ScheduleSlot',
  'ExtracurricularActivity',
  'StudentClassAssignment',
  'ClassDecisionThreshold',
  'Grade',
  'PreschoolGrade',
  'Expense',
  'FileMetadata',
  'Attendance',
  'PaymentTransaction',
];
